# Generated by Django 3.0.5 on 2020-04-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='thumb',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
