# Generated by Django 3.0.5 on 2020-04-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200424_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='thumb',
            field=models.ImageField(upload_to='media'),
        ),
    ]
